### ISSUE TITLE
No matching distribution found for tvfeed-1.0.0-py3.8.egg

### ISSUE THREAD

**Issue by ssantoshp** [StreamAlpha/tvdatafeed_nologin#3]
When I do `pip install tvfeed-1.0.0-py3.8.egg ` it gives me this:
![image](https://user-images.githubusercontent.com/61618641/119318241-56e75d00-bc79-11eb-9c0c-78a9760737c9.png)

I also tried `easy_install tvfeed-1.0.0-py3.8.egg ` and it also creates en error:
![image](https://user-images.githubusercontent.com/61618641/119318289-66ff3c80-bc79-11eb-9954-c7e05fe02d67.png)

How can I fix that?

**Comment by StreamAlpha** [comment]
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@develop
