### ISSUE TITLE
ModuleNotFoundError: No module named 'tvfeed'

### ISSUE THREAD

**Issue by ssantoshp** [StreamAlpha/tvdatafeed_nologin#4]
I did ```pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@develop``` and then it gave me that:

![Capture](https://user-images.githubusercontent.com/61618641/119872817-2c6cfc80-bf24-11eb-9871-bbd86c7de2c5.JPG)

My tv.py looks like:

```py
from tvfeed import TvDatafeed, Interval

tv=TvDatafeed()

print(tv.get_hist('AAPL','NASDAQ'))
```
Where did I go wrong, please?

**Comment by StreamAlpha** [comment]
it was a small typo in the code.
fixed that
```
from tvDatafeed import TvDatafeed,Interval

username = 'YourTradingViewUsername'
password = 'YourTradingViewPassword'



tv=TvDatafeed(username, password)
```

**Comment by ssantoshp** [comment]
But then, we have to log in to get data. Is there a way to do that without username+password?
