### ISSUE TITLE
Not able to get futures data for MCX exchange instruments!

### ISSUE THREAD

**Issue by youngking1686** [StreamAlpha/tvdatafeed_nologin#5]
Hi,
I am able to get data for cash and futures data from NSE, but the same isn't working for MCX can you please check ? getting the below error

print(tv.get_hist(symbol='CRUDEOIL', exchange='MCX', interval=Interval.in_15_minute, n_bars=50, fut_contract=1))

response error:
.....................\python38\lib\site-packages\tvfeed-1.0.0-py3.8.egg\tvfeed\main.pyc in get_hist(cls, symbol, exchange, interval, n_bars, fut_contract)
.....................\python38\lib\site-packages\tvfeed-1.0.0-py3.8.egg\tvfeed\main.pyc in __create_df(raw_data, symbol)
AttributeError: 'NoneType' object has no attribute 'group'

Thanks for the library.

**Comment by StreamAlpha** [comment]
for MCX data you need to be logged in.
check this out for new version installation and manual login
https://youtu.be/f76dOZW2gwI
